spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
#    url: jdbc:h2:mem:testdb
    jdbc-url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.H2Dialect #extra code
      hibernate:
#        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect #extra code
    defer-datasource-initialization: true #extra code
    open-in-view: false #extra code

logging:
  level:
    org.hibernate.SQL: debug